# Generated by Django 5.1 on 2024-08-22 20:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('test_date', models.DateField(default=datetime.date(2024, 8, 22))),
                ('report', models.FileField(upload_to='medical_reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_low', models.CharField(blank=True, max_length=10, null=True)),
                ('reference_high', models.CharField(blank=True, max_length=10, null=True)),
                ('result', models.CharField(max_length=20)),
                ('medical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_analysis.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('medical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_analysis.medicalreport')),
            ],
        ),
    ]
