# Generated by Django 5.1 on 2024-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattributes',
            name='reference_high',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportattributes',
            name='reference_low',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportattributes',
            name='result',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportattributes',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
