# Generated by Django 5.1 on 2024-11-01 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_analysis', '0003_alter_medicalreport_test_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportCategory',
            new_name='Treatment',
        ),
        migrations.RenameField(
            model_name='medicalreport',
            old_name='category',
            new_name='treatment',
        ),
    ]
